-- Seed data mirroring src/lib/mock-data.ts.
-- Run after 0001_init.sql.

insert into public.categories (slug, name, tagline, description, image, accent, position) values
  ('bouquets-signature','Bouquets signature','Compositions de l''atelier',
   'Compositions saisonnières montées à la main par Jules, dans l''esprit champêtre et structuré qui fait la signature de la maison.',
   'https://images.unsplash.com/photo-1487070183336-b863922373d4?auto=format&fit=crop&w=1600&q=80','forest',1),
  ('roses','Roses de jardin','Variétés anciennes & parfumées',
   'Des roses de Pierre de Ronsard à la David Austin, sélectionnées chez nos producteurs partenaires en Île-de-France.',
   'https://images.unsplash.com/photo-1496062031456-07b8f162a322?auto=format&fit=crop&w=1600&q=80','bloom',2),
  ('plantes','Plantes d''intérieur','Verdure pour la maison',
   'Monstera, oliviers nains, fougères et plantes rares — chacun choisi pour son port et sa robustesse.',
   'https://images.unsplash.com/photo-1463936575829-25148e1db1b8?auto=format&fit=crop&w=1600&q=80','sage',3),
  ('mariage','Mariage & événement','Sur mesure',
   'Bouquets de mariée, arches florales et compositions pour vos cérémonies. Devis personnalisé sous 48h.',
   'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1600&q=80','terracotta',4),
  ('deuil','Hommage','Avec délicatesse',
   'Couronnes, gerbes et coussins pour accompagner les moments les plus délicats. Livraison directe au lieu de cérémonie.',
   'https://images.unsplash.com/photo-1494972308805-463bc619d34e?auto=format&fit=crop&w=1600&q=80','sage',5),
  ('abonnements','Abonnements','Chaque semaine',
   'Recevez chez vous un bouquet de saison toutes les semaines, deux semaines ou tous les mois. Sans engagement.',
   'https://images.unsplash.com/photo-1453747063559-36695c8771bd?auto=format&fit=crop&w=1600&q=80','forest',6)
on conflict (slug) do nothing;

insert into public.products (slug,name,category_slug,price_cents,description,long_description,images,composition,size,in_stock,featured) values
  ('bouquet-aurore','Bouquet Aurore','bouquets-signature',6500,
   'Pivoines, roses anciennes, eucalyptus.',
   'Aurore évoque la lumière du matin sur le jardin. Pivoines roses poudrées, roses David Austin, eucalyptus parvifolia et touches de gypsophile. Monté en spirale main, livré dans un papier kraft écru et un ruban de soie.',
   array['https://images.unsplash.com/photo-1525310072745-f49212b8ac81?auto=format&fit=crop&w=1400&q=80','https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&w=1400&q=80','https://images.unsplash.com/photo-1487070183336-b863922373d4?auto=format&fit=crop&w=1400&q=80'],
   array['Pivoines','Roses David Austin','Eucalyptus parvifolia','Gypsophile'],
   'M',true,true),
  ('bouquet-fougere','Bouquet Fougère','bouquets-signature',5500,
   'Renoncules, fougères, branches de saule.',
   'Composition graphique et champêtre autour des verts profonds : fougères Boston, renoncules ivoire, saule tortueux. Idéal pour une table d''intérieur ou un cadeau qui sort des sentiers battus.',
   array['https://images.unsplash.com/photo-1508610048659-a06b669e3321?auto=format&fit=crop&w=1400&q=80','https://images.unsplash.com/photo-1453747063559-36695c8771bd?auto=format&fit=crop&w=1400&q=80'],
   array['Renoncules ivoire','Fougères Boston','Saule tortueux'],
   'M',true,false),
  ('bouquet-cinq-heures','Bouquet Cinq Heures','bouquets-signature',8200,
   'Dahlias, lisianthus, herbes folles.',
   'Le bouquet de la fin d''après-midi, quand la lumière s''adoucit. Dahlias bordeaux, lisianthus crème, herbes folles et fenouil sauvage. Volume généreux, pour une grande pièce de réception.',
   array['https://images.unsplash.com/photo-1502977249166-824b3a8a4d6d?auto=format&fit=crop&w=1400&q=80','https://images.unsplash.com/photo-1542816417-0983c9c9ad53?auto=format&fit=crop&w=1400&q=80'],
   array['Dahlias bordeaux','Lisianthus crème','Fenouil sauvage','Herbes folles'],
   'L',true,true),
  ('rose-pierre-ronsard','Roses Pierre de Ronsard','roses',4800,
   'Botte de 12 roses anciennes parfumées.',
   'La rose des roses. Coupées le matin même chez notre producteur en Eure-et-Loir, elles s''épanouissent en cœur double, rose tendre et crème. Tiges 50 cm minimum.',
   array['https://images.unsplash.com/photo-1496062031456-07b8f162a322?auto=format&fit=crop&w=1400&q=80','https://images.unsplash.com/photo-1494972308805-463bc619d34e?auto=format&fit=crop&w=1400&q=80'],
   array['12 tiges de roses Pierre de Ronsard'],
   'M',true,true),
  ('rose-juliette','Roses Juliette','roses',5200,
   'Botte de 9 roses David Austin.',
   'Roses Juliette de David Austin, abricot poudré au cœur, parfum de pêche et de myrrhe. Botte de 9 tiges, idéale en monobouquet sur une desserte.',
   array['https://images.unsplash.com/photo-1494972308805-463bc619d34e?auto=format&fit=crop&w=1400&q=80'],
   array['9 tiges de roses Juliette'],
   'M',true,false),
  ('monstera-deliciosa','Monstera Deliciosa','plantes',7500,
   'Grand sujet, pot terre cuite inclus.',
   'Une grande Monstera Deliciosa de 80 cm avec ses feuilles découpées caractéristiques. Livrée en pot de terre cuite naturelle Ø 24 cm, terreau biologique enrichi.',
   array['https://images.unsplash.com/photo-1463936575829-25148e1db1b8?auto=format&fit=crop&w=1400&q=80','https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=1400&q=80'],
   array['Monstera Deliciosa 80cm','Pot terre cuite Ø24','Terreau bio'],
   'L',true,false),
  ('olivier-de-provence','Olivier de Provence','plantes',12000,
   'Tronc tressé, hauteur 1m20.',
   'Olivier d''extérieur ou véranda, tronc tressé, taillé en boule. Hauteur 1m20. Une présence sculpturale qui traverse les années.',
   array['https://images.unsplash.com/photo-1542856204-00101eb6def4?auto=format&fit=crop&w=1400&q=80'],
   array['Olivier 1m20','Pot terracotta Ø32'],
   'L',false,false),
  ('bouquet-mariee-blanche','Bouquet Mariée Blanche','mariage',14500,
   'Pivoines, roses ivoire, lisianthus.',
   'Bouquet rond intemporel pour mariée. Pivoines ivoire, roses David Austin Patience, lisianthus blanc, eucalyptus argenté. Tige enrubannée de soie sauvage.',
   array['https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1400&q=80'],
   array['Pivoines ivoire','Roses Patience','Lisianthus','Eucalyptus argenté'],
   'L',true,true),
  ('couronne-hommage','Couronne Hommage','deuil',16000,
   'Couronne ronde Ø60cm, ton sur ton.',
   'Couronne ronde Ø60cm, composition ton sur ton de roses ivoire, lisianthus, eucalyptus et feuillages doux. Livraison directe au lieu de cérémonie sous 24h.',
   array['https://images.unsplash.com/photo-1494972308805-463bc619d34e?auto=format&fit=crop&w=1400&q=80'],
   array['Roses ivoire','Lisianthus','Eucalyptus','Feuillages'],
   'L',true,false),
  ('abonnement-hebdo','Abonnement hebdomadaire','abonnements',4500,
   'Un bouquet de saison chaque semaine.',
   'Chaque jeudi, recevez un bouquet de saison composé par Jules. Sans engagement, suspension à tout moment depuis votre compte. Livraison Paris incluse.',
   array['https://images.unsplash.com/photo-1453747063559-36695c8771bd?auto=format&fit=crop&w=1400&q=80'],
   array['Bouquet hebdomadaire','Livraison Paris incluse'],
   'M',true,true)
on conflict (slug) do nothing;
